spring:
  datasource:
    url: jdbc:mysql://47.112.11.98:3306/promets?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
logging:
  level: # SpringBoot默认配置了slf4j，不同目录下的日志可配置不同级别 info、debug、error、warn、trace
    root: info
