spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
wx:
  config: # Here may be warning cannot resolve property, Just run and it will be disappear.
    appId: wx3e27ee2b8839dffb
    appSecret: 998a35c708611f8d0c1db1d1942677fd
    code2SessionBaseUrl: https://api.weixin.qq.com
mybatis:
  typeAliasesPackage: ltd.jezhu.promets.dao
  mapperLocations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: varchar
    default-fetch-size: 100
    default-statement-timeout: 10
server:
  port: 8088
  servlet:
    context-path: /promets
jwt:
  config: # Here may be warning cannot resolve property, Just run and it will be disappear.
    secret: a25c31c9-5220-4757-8f4b-b9b71acd0884
    expires: 3600000
    iss: iss
    aud: aud
# FastDFS配置
fdfs:
  soTimeout: 1500 # socket连接超时时长
  connectTimeout: 600 # 连接tracker服务器超时时长
  trackerList: # TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 47.99.221.200:22122
  web-server-url: http://47.99.221.200:8888/ # FDFS中的nginx的ip和port
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ltd.jezhu.promets.base.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    use-column-label: true
  global-config:
    db-config:
      table-underline: true